org.gradle.jvmargs=-Xmx4096M
loom.ignoreDependencyLoomVersionValidation=true

# List of Enables for things revolving around sub directories or run configs for specific platforms

# Adds a mixin debugging run for the given platform allowed
enabled_mixin_debugging_platforms=fabric
# Adds renderdoc debugging run using owolib
enabled_renderdoc_debugging_platforms=fabric
# Adds test mod for designed platform
enabled_testmod_platforms=

enabled_platforms=fabric,neoforge

enabled_item_viewers=emi,rei
# Types: none, rei, emi, jei
selected_item_viewers=none

# Mod information starts here

mod_id=alloy-forgery
mod_group=io.wispforest
mod_version=3.0.6

mod_name=Alloy Forgery
mod_description=Adds an Alloy Forge for blasting ores and forging alloys

mod_license=MIT
# TODO: ADD LINK TO TEMPLATE
mod_homepage=https://github.com/wisp-forest/alloy-forgery
# TODO: ADD LINK TO TEMPLATE
mod_sourcepage=https://github.com/wisp-forest/alloy-forgery
# TODO: ADD LINK TO TEMPLATE
mod_issuepage=https://github.com/wisp-forest/alloy-forgery/issues

# List of Authors separated by commas (,)
mod_authors=blodhgarm,Noaaan
# List of Contributors separated by commas (,)
mod_contributors=glisco,LordDeatHunter
# List of Credited People or Organizations separated by commas (,) or blank if not applicable
mod_credits=

# List of Authors/Creditors Contact Links base on the given format: {author_name}={link_to_page}
# Requires any spaces are set to underscores (_) and all upper cases letters are lowercased
blodhgarm=https://github.com/Dragon-Seeker
noaaan=https://github.com/Noaaan
glisco=https://github.com/gliscowo
lorddeathunter=https://github.com/LordDeatHunter

test_mod_id=alloy-forgery-testing